[tools]
cosign = "latest"
atuin = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
jq = "latest"
jqp = "latest"
k9s = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
starship = "latest"
viddy = "latest"
yq = "latest"
carapace = "latest"
btop = { version = "latest", os = ["linux"] }
eza = { version = "latest", os = ["linux"] }
bitwarden = { version = "latest", os = ["macos"] }
