["nvim"]
    type = "git-repo"
    url = "https://github.com/LaurentHrt/kickstart.nvim.git"
    exact = true
    stripComponents = 1
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
